// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruzebhpdrjnrbpkpmcvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1emViaHBkcmpucmJwa3BtY3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjg0NTgsImV4cCI6MjA2Nzk0NDQ1OH0.7bZrehhi19om7wZ7dwCOfDaTRYtsd224-dJqf4etW2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});